### ISSUE TITLE
Status keeps saying registering

### ISSUE THREAD

**Issue by ChimorinNL** [SquirrelCorporation/SquirrelServersManager#10]
I've managed to add my Ubuntu server yesterday. Its been about 14 hours now, but it keeps saying its registering. I've checked the agent, but everything seems to be installed fine. Agent server is also able to ping and connect to the Manager server.

![image](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/33694551/6abcd02d-4f57-4bbc-8cd1-35b1ab4ba017)

Also tried to grab agent logs, but ansible says it has no content:

![image](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/33694551/220a6509-ccc3-46be-be95-2ba7d4d552c4)

**Comment by SquirrelCorporation** [comment]
Hi @ChimorinNL !
Are you able to provide the logs of the agent on the host?
THey should be in /opt/squirrelserversmanager/logs or /opt/squirrelserversmanager/build/logs ?
If not, could you try the manual install https://squirrelserversmanager.io/docs/manual-install-agent and provide the logs?
Thanks

**Comment by ChimorinNL** [comment]
Hi! I tried to look it up, but i cant find any logs in any of the directories. Tried to reinstall, and manually install, but no logs.

**Comment by SquirrelCorporation** [comment]
Hi, try to execute in `/opt/squirrelserversmanager` 
```
npm install
npm run dev
```

**Comment by ChimorinNL** [comment]
This is the error i get when executing npm run dev:

![image](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/33694551/6d9c1813-654f-4770-b2bc-932e12eb51ac)

**Comment by SquirrelCorporation** [comment]
You can either update the agent with git pull and retry, I have updated the repo so nodemon is included in the dev dependencies, or install it globally on the host with `npm install -g nodemon` and retry

**Comment by SquirrelCorporation** [comment]
I have published a new version with testing of connection on the add device modal/flow, the installation of agent is managed by Ansible code directly now, to make it easier to debug

**Comment by ChimorinNL** [comment]
I've updated the server with git pull and docker compuse up --build, then reinstalled the agent by adding it via Ansible, but still registering result. Also did npm install && npm run dev on the agent, also no better result.

![image](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/33694551/d31082db-24dc-41f5-aeef-a8b324548b76)

**Comment by NathanBeirens** [comment]
I have the same issue, 2 servers (lxc, debian 12) stuck on registering.
Agent install went smooth on a clean lxc debian 12 server.

(all my agent installs where done from the server gui)

pm2 logs agent gives me this log on the ones stuck on registering.
Is there a way we can check which master api url the agent is using?

![image](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/10890669/c8e956dd-0f41-4c4c-8d1c-904ff63a4635)

**Comment by SquirrelCorporation** [comment]
Yeah, this is likely due to an outdated NodeJs version.
Could you indicate the result of 
`node -v` 
`npm -v` 

To investigate further, could you also, on the device, show the logs of
`cd /opt/squirrelserversmanager`
`npm install`
`npm run dev`

And
`cd /opt/squirrelserversmanager`
`npm run build`
` pm2 start -f "./build/agent.js"`
`pm2 list`

?

**Comment by ChimorinNL** [comment]
On the agent client for me its:
Node: 10.19.0
NPM: 6.14.4

**Comment by ChimorinNL** [comment]
Hi! Upgraded my version of node to version 18, then installed via the script and worked immediatly! Thank you, very stupid of me not to think of this.
