### ISSUE TITLE
[Question] Is RAM percentage displayed on dashboard based on available or free RAM

### ISSUE THREAD

**Issue by Buco7854** [SquirrelCorporation/SquirrelServersManager#100]
Sometimes RAM is being used for cache and can appear as RAM being used when its actually available (can see that using `free -h`). Does SquirelServersManager display the RAM actually being used or does it exclude "Cached RAM".

**Comment by SquirrelDeveloper** [comment]
Hi @Buco7854 - As far I can tell, the lib node-os-utils call `/prod/meminfo`
total mem available is computed as follow : 
```
memInfo['MemFree'] + memInfo['Buffers'] + memInfo['Cached'] + memInfo['SReclaimable'] - memInfo['Shmem'];
```
then mem % : 
```
var freeMemPercentage = parseFloat((100 * (freeMem / totalMem)).toFixed(2))
```
with freeMem being from the default os node package https://nodejs.org/api/os.html#osfreemem

**Comment by SquirrelDeveloper** [comment]
We may change that by using a better maintain package, systeminformation, that does offer the possibility to exclude swap
https://systeminformation.io/memory.html

**Comment by Buco7854** [comment]
I see, just wanted to know regarding the stats I had.

That would be awesome but not like it's a priority.

Thank you.

**Comment by SquirrelDeveloper** [comment]
Added to backlog https://github.com/SquirrelCorporation/SquirrelServersManager/issues/101
