### ISSUE TITLE
Consider hosted docker images

### ISSUE THREAD

**Issue by anarion80** [SquirrelCorporation/SquirrelServersManager#12]
Please consider automatically building images in CI and hosting them on Docker Hub or directly here on ghcr.io.

**Comment by SquirrelCorporation** [comment]
@anarion80 The docker-compose file has been updated and package has been published

**Comment by hoferbeck** [comment]
Is there a reason why the Proxy isnt in a hosted Container Image? 

And I would appreciate if there would be an example with the Traefik reverse proxy

**Comment by anarion80** [comment]
I suspect it's because of the index.html file that comes with SquirrelServersManager. I worked around this in my fork of [Ansible-NAS](https://github.com/anarion80/ansible-nas) by using a hosted Nginx image and just providing the config and index file manually (or as in this case - automatically via Ansible): https://github.com/anarion80/ansible-nas/blob/main/roles/squirrel/tasks/main.yml
