### ISSUE TITLE
[FEATURE]  - Docker Compose without a NginX Reverse Proxy

### ISSUE THREAD

**Issue by AX-AMote** [SquirrelCorporation/SquirrelServersManager#139]
Just wondering if having a deployment available that does not include a reverse proxy?

I can definitely see the rationale in including a reverse proxy in order to help users get started faster, but it actually makes deployment more difficult.

If somebody already has a reverse proxy at the edge of their network handling SSL termination etc, then another reverse proxy makes this service two reverse proxy layers in and messes up the flow and complexity.

Some use Traefik, NGINx Proxy Manager, Zoraxy, HAProxy, Caddy, NGinX, OPNSense Plugins, etc.

I will gladly contribute my docker-compose.yml file after constructed to the repo if you can guide me on how to deploy without the included NGINx?

**Comment by freedbygrace** [comment]
ok perfect! Good to know! Is there any way to provide an example where the frontend container is on 8000 and the backend is on 3000. Then I can put my own reverse proxy in front of the service and expose the WebUI by creating a routing rule pointing to port 8000 which can then talk to the back-end service on 3000 but remain safely within the private network.

**Comment by SquirrelDeveloper** [comment]
@freedbygrace Yes, I managed a proxy free configuration.

- Here you can see the docker compose file : https://github.com/SquirrelCorporation/SquirrelServersManager/compare/test-changing-ports?expand=1#diff-4563fbe997bbf18c3b38ad79c596c57c3ad88361f1dccb8c4f39b429382c06d3
- You are gonna need to set the URL API in the React code here https://github.com/SquirrelCorporation/SquirrelServersManager/compare/test-changing-ports?expand=1#diff-498b678a5aa69765cfe1c060d6b7ceb701ff74a473039cb8299aa635ec5027daR83
- And changing the server root path https://github.com/SquirrelCorporation/SquirrelServersManager/compare/test-changing-ports?expand=1#diff-113afe997c4a5828a07dff52fff0b73f7fad5b005a2953e0823a9bb00d7f5283R52

Full example with CORS, etc... https://github.com/SquirrelCorporation/SquirrelServersManager/compare/test-changing-ports?expand=1
