### ISSUE TITLE
[BUG] No Playbook starts on a certain host

### ISSUE THREAD

**Issue by sahara101** [SquirrelCorporation/SquirrelServersManager#164]
**Describe the bug**
Hello. I want to add a turnkey lxc container to my devices list. It never finished any playbook I throw at it. No errors I can see. 

** Logs **
`Starting...
ansible-playbook [core 2.17.0]
config file = /server/src/ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.12/site-packages/ansible
ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible-playbook
python version = 3.12.3 (main, Apr 18 2024, 07:52:31) [GCC 13.2.1 20240309] (/usr/bin/python3)
jinja version = 3.1.4
libyaml = True
Using /server/src/ansible/ansible.cfg as config file
Reading vault password file: /server/src/ansible/ssm-ansible-vault-password-client.py
The vault password file /server/src/ansible/ssm-ansible-vault-password-client.py is a client script.
Executing vault password client script: /server/src/ansible/ssm-ansible-vault-password-client.py --vault-id default
setting up inventory plugins
Loading collection ansible.builtin from
host_list declined parsing /server/src/ansible/inventory/hosts.json as it did not pass its verify_file() method
script declined parsing /server/src/ansible/inventory/hosts.json as it did not pass its verify_file() method
auto declined parsing /server/src/ansible/inventory/hosts.json as it did not pass its verify_file() method
Parsed /server/src/ansible/inventory/hosts.json inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3.12/site-packages/ansible/plugins/callback/default.py
Loading callback plugin awx_display of type stdout, v2.0 from /usr/lib/python3.12/site-packages/ansible_runner/display_callback/callback/awx_display.py
Attempting to use 'awx_display' callback.
Skipping callback 'awx_display', as we already have a stdout callback.
Attempting to use 'default' callback.
Skipping callback 'default', as we already have a stdout callback.
Attempting to use 'junit' callback.
Attempting to use 'minimal' callback.
Skipping callback 'minimal', as we already have a stdout callback.
Attempting to use 'oneline' callback.
Skipping callback 'oneline', as we already have a stdout callback.
Attempting to use 'tree' callback.
PLAYBOOK: _installAgent.yml ****************************************************
Positional arguments: /server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_installAgent.yml
verbosity: 5
connection: ssh
become_method: sudo
tags: ('all',)
inventory: ('/server/src/ansible/inventory/hosts.json',)
extra_vars: ('@/server/src/ansible/env/extravars', '{"_ssm_masterNodeUrl":"https://squirrel.rlvd.duckdns.org","_ssm_deviceId":"016f6eb9-d729-47a1-be03-5bc405e67ee1"}')
vault_password_files: ('/server/src/ansible/ssm-ansible-vault-password-client.py',)
forks: 5
1 plays in /server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_installAgent.yml
PLAY [Install agent on targeted device] ****************************************
TASK [Install agent on targeted device] ****************************************
task path: /server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_installAgent.yml:10
 ok: [192.168.1.21] => {
  "msg": "Host ID 016f6eb9-d729-47a1-be03-5bc405e67ee1 with API URL https://squirrel.rlvd.duckdns.org"
}
TASK [Check if NodeJS is installed] ********************************************
task path: /server/src/ansible/00000000-0000-0000-0000-000000000000/agent/_installAgent.yml:14
<192.168.1.21> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: root on PORT 22 TO 192.168.1.21
<192.168.1.21> EXEC /bin/sh -c 'echo ~root && sleep 0'
<192.168.1.21> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1723286681.4718711-2962-197277803052105 `" && echo ansible-tmp-1723286681.4718711-2962-197277803052105="` echo /root/.ansible/tmp/ansible-tmp-1723286681.4718711-2962-197277803052105 `" ) && sleep 0'
Including module_utils file ansible/__init__.py
Including module_utils file ansible/module_utils/__init__.py
Including module_utils file ansible/module_utils/basic.py
Including module_utils file ansible/module_utils/_text.py
Including module_utils file ansible/module_utils/common/_utils.py
Including module_utils file ansible/module_utils/common/__init__.py
Including module_utils file ansible/module_utils/common/arg_spec.py
Including module_utils file ansible/module_utils/common/collections.py
Including module_utils file ansible/module_utils/common/file.py
Including module_utils file ansible/module_utils/common/locale.py
Including module_utils file ansible/module_utils/common/parameters.py
Including module_utils file ansible/module_utils/common/process.py
Including module_utils file ansible/module_utils/common/sys_info.py
Including module_utils file ansible/module_utils/common/text/converters.py
Including module_utils file ansible/module_utils/common/text/__init__.py
Including module_utils file ansible/module_utils/common/text/formatters.py
Including module_utils file ansible/module_utils/common/validation.py
Including module_utils file ansible/module_utils/common/warnings.py
Including module_utils file ansible/module_utils/compat/selinux.py
Including module_utils file ansible/module_utils/compat/__init__.py
Including module_utils file ansible/module_utils/distro/__init__.py
Including module_utils file ansible/module_utils/distro/_distro.py
Including module_utils file ansible/module_utils/errors.py
Including module_utils file ansible/module_utils/parsing/convert_bool.py
Including module_utils file ansible/module_utils/parsing/__init__.py
Including module_utils file ansible/module_utils/pycompat24.py
Including module_utils file ansible/module_utils/six/__init__.py
<192.168.1.21> Attempting python interpreter discovery
<192.168.1.21> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.12'"'"'; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python3'"'"'; echo ENDFOUND && sleep 0'
<192.168.1.21> Python interpreter discovery fallback (pipelining support required for extended interpreter discovery)
Using module file /usr/lib/python3.12/site-packages/ansible/modules/command.py
<192.168.1.21> PUT /root/.ansible/tmp/ansible-local-2957uv1fpm88/tmpwdxdvc5u TO /root/.ansible/tmp/ansible-tmp-1723286681.4718711-2962-197277803052105/AnsiballZ_command.py
<192.168.1.21> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1723286681.4718711-2962-197277803052105/ /root/.ansible/tmp/ansible-tmp-1723286681.4718711-2962-197277803052105/AnsiballZ_command.py && sleep 0'
$`

**Expected behavior**
Host to be added as all the others. 
**Screenshots**

**Comment by SquirrelDeveloper** [comment]
Hi,
Thanks very much for your feedback,
The given logs doesn't seem to include the error, could you give me the full stack (logs) trace, with the error?
Thanks

**Comment by SquirrelDeveloper** [comment]
@sahara101 I am playing with turnkey, which exact version are you using?

**Comment by SquirrelDeveloper** [comment]
@sahara101 I have reproduced the issue.
I dont know exactly why it is not working using the ansible ssh connection method 'paramiko', so I opened an issue on the Ansible github.
However, using the default connection method is working for those kinds of hosts. So i added an option in the SSH configuration modal (Inventory/Configuration then toggle the 'advanced' option) so you can setup the 'SSH' builtin method
<img width="895" alt="Screenshot 2024-08-22 at 09 17 32" src="https://github.com/user-attachments/assets/05d4cd0c-eeec-4a1b-a567-b5b9f31091ad">

**Comment by sahara101** [comment]
Thank you, will try it out.
