### ISSUE TITLE
[BUG] Adding all LXCs and VMs very high CPU load

### ISSUE THREAD

**Issue by sahara101** [SquirrelCorporation/SquirrelServersManager#165]
**Describe the bug**
After adding all of my proxmox LXCs and VMs to squirrel, the load average goes above 100. CPU has 20 cores. Stopping with pm2 stop -f /opt/squirrelserversmanager/build/agent.js makes the load average go down to normal values. 

Right now I am forced to disable all squirrel connections :(

**Comment by SquirrelDeveloper** [comment]
Will take a look at it very soon

**Comment by SquirrelDeveloper** [comment]
@sahara101 Hi, So far, I have not noticed any changes in CPU on Proxmox. Could you tell me more precisely your setup? Did you install the agent on the bare metal server running proxmox? Do you have some kind of paid version? A cluster?

**Comment by sahara101** [comment]
Hi, I installed the agent on all LXCs (22) and VMs (2). Standard Proxmox, o cluster. Proxmox itself is installed on a MS-01 12900h i9

**Comment by SquirrelDeveloper** [comment]
I am closing it as I dont reproduce at all
