### ISSUE TITLE
Server in docker keeps restarting - can't connect to mongo

### ISSUE THREAD

**Issue by anarion80** [SquirrelCorporation/SquirrelServersManager#17]
Server keeps restarting after docker install:

```
Node.js v22.2.0
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:events:498
      throw er; // Unhandled 'error' event
      ^
MongoServerSelectionError: getaddrinfo EAI_AGAIN mongo
    at Timeout._onTimeout (/server/node_modules/pino-mongodb/node_modules/mongodb/lib/sdam/topology.js:292:38)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on ThreadStream instance at:
    at Immediate.<anonymous> (/server/node_modules/thread-stream/index.js:369:12)
    at process.processImmediate (node:internal/timers:478:21)
```

At first glance this seems to be related to `mongo` being hardcoded in here: https://github.com/SquirrelCorporation/SquirrelServersManager/blob/9ec3cf586fd3752929267a5d95fb737ad339b822/server/src/logger.ts#L14

while I'm using DB_HOST env variable and a different name than `mongo`

**Comment by SquirrelCorporation** [comment]
Hi @anarion80 Thanks a lot for the feedback, and pointing the mistake
I have published a new version we the fix, if you could confirm it resolves the problem,

**Comment by anarion80** [comment]
Ok, I will wait for the docker images to be rebuilt and then check.

**Comment by anarion80** [comment]
Ok, it works now 👍🏻 

I added Squirrel Servers Manager to my fork of Ansible-NAS: https://github.com/anarion80/ansible-nas/pull/167
