### ISSUE TITLE
[FEATURE] Manage a remote device

### ISSUE THREAD

**Issue by Nonobis** [SquirrelCorporation/SquirrelServersManager#214]
**Is your feature request related to a problem? Please describe.**
i am still reviewing Squirrel Servers Manager.
I like what i saw for now, ui is clean and beautiful and i don't known ansilble but it's seem an insteresting feature.
My main probleme and i want to manage remote server over internet with Squirrel Server Manager.
if i understand correctly it's not possible, i can only connect local network server ... Do you think it could be possible ?

**Describe the solution you'd like**
A installable agent who connect over exposed fqdn via reverse proxy

**Describe alternatives you've considered**
Anything you like :)

**Comment by SquirrelDeveloper** [comment]
Hi @Nonobis . Does the server has an available public IP? If yes, it should work

**Comment by Nonobis** [comment]
@SquirrelDeveloper Yes but only 443/80 opened, do i need a specific port ?

**Comment by SquirrelDeveloper** [comment]
You could (22) but I would **not** recommend it **at all** to expose the SSH port on an internet exposed server, _unless_ you have a firewall or iptables what can whitelist which IP can access to the port. 
In the future, the agent will be reworked, I will keep your feedback in mind

**Comment by aobxc** [comment]
Hello @SquirrelDeveloper ,

I'm trying to achieve the same thing as the person who opened this request and have successfully installed the agent remotely, but there is a problem:

The device's IP has automatically changed into it's LAN IP, making it so I cannot open a ssh session from ssm:
![image](https://github.com/user-attachments/assets/a09b5478-5e87-4b8c-ad4a-ec1592b1bd1c)

I've tried changing back it's IP, but it's greyed out and I cannot type into the text box.

Any thoughts?

**Comment by aobxc** [comment]
Hello @SquirrelDeveloper ,

It worked, thanks ^^
