### ISSUE TITLE
[FEATURE] Compatibility for docker environments with a TLS Configuration

### ISSUE THREAD

**Issue by SpasianNrD** [SquirrelCorporation/SquirrelServersManager#218]
**Is your feature request related to a problem? Please describe.**
In my environment, all docker sockets are configured behind TLS Certificates. Currently docker services/containers won't update or show for any of my machines/vms. Volumes, Networks, and Images do update after SSM restart or host recheck.

**Describe the solution you'd like**
Allow to the option to connect to the docker sockets with TLS certificate configuration.

**Describe alternatives you've considered**
Not having the agent connect via the socket at all, running through docker information with just cli commands in the connection strings.

**Additional context**
The TLS setup for docker is outlined here: ([x](https://docs.docker.com/engine/security/protect-access/))

**Comment by SquirrelDeveloper** [comment]
@SpasianNrD Yes, the underlying library is supporting certificates, so I will add this feature in the next version

**Comment by SquirrelDeveloper** [comment]
Added in a future release v0.1.18

**Comment by SquirrelDeveloper** [comment]
@SpasianNrD The version has been released, doc updated https://squirrelserversmanager.io/docs/technical-guide/docker-connection
