### ISSUE TITLE
Device Configuration shows SSH Private Key

### ISSUE THREAD

**Issue by Codycody31** [SquirrelCorporation/SquirrelServersManager#22]
![image](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/77461086/ef094e39-6ff0-4f08-b1ce-b53b2a4d91ce)

Similar to how the super user password is handled the ssh private key should also use a placeholder unless it is being updated.

**Comment by SquirrelCorporation** [comment]
The new version, currently building, will completely prevent sensitive information from being send from back to front
