### ISSUE TITLE
[BUG]  Encounter "Response status: 500 - ExtraVar value not found !" while trying to add a new server. 

### ISSUE THREAD

**Issue by niyoh120** [SquirrelCorporation/SquirrelServersManager#296]
**Describe the bug**
Encounter "Response status: 500 - ExtraVar value not found !" while trying to add a new server. 

** Logs **
![image](https://github.com/user-attachments/assets/e7d890e3-e431-419b-8881-7bd835f7a0f9)

**To Reproduce**
![image](https://github.com/user-attachments/assets/7d721872-9d5e-4fbb-85a7-5d0a8e6fa0d4)

**Screenshots**
![image](https://github.com/user-attachments/assets/7d721872-9d5e-4fbb-85a7-5d0a8e6fa0d4)

**(please complete the following information):**
 - OS: docker on debian12
 - Browser chrome
 - Version 0.1.18

**Comment by SquirrelDeveloper** [comment]
@niyoh120 Thank you for the report, the bug has been identified and fixed in v0.1.19,
Just do a docker compose pull to retrieve the new version

**Comment by JzJad** [comment]
Just wanted to add getting the same error with re-install agent, on v0.1.19.

**Comment by SquirrelDeveloper** [comment]
@JzJad Hi, thanks for the report,
I am not reproducing on my end, could you try:

- Going In `Settings` ; `Playbooks`

<img width="1422" alt="Screenshot 2024-09-30 at 09 15 22" src="https://github.com/user-attachments/assets/18fb2167-86eb-46a7-b0ea-f7c6051b0e4b">

- Then click on `ssm-core` ; then click on the tree dots of the action button ; and click to `Sync to database`

<img width="810" alt="Screenshot 2024-09-30 at 09 15 31" src="https://github.com/user-attachments/assets/d5264e5b-6033-45b1-849c-005f779a18d0">

Does that solve the problem?

**Comment by SquirrelDeveloper** [comment]
Yeah, you could wipe the `.data.prod` directory to  do a 'factory reset' and test from there :-)

**Comment by JzJad** [comment]
That did it, at least adding agents is all good for me, will report any bugs if found! 😄
