### ISSUE TITLE
[BUG] Only 10 hosts available for automation

### ISSUE THREAD

**Issue by btajuddin** [SquirrelCorporation/SquirrelServersManager#319]
**Describe the bug**
Using the UI, you can only add hosts from the first 10 in the devices list as targets for the automation task. This appears to be because the default page size is 10, and the dropdown is not configured to read other pages from the server.

** Logs **
N/A

**To Reproduce**
1. Add more than 10 hosts
2. Go to the devices page and find a host after page 1
3. Go to Automations
4. Click "Create a new automation"
5. Select a trigger
6. Select a playbook
7. In the host selection, try to select the host from after page 1 (step 2). It won't show up in the list.
8. Try typing the name of the host from step 2 into the box. It won't show up and cannot be saved.

**Expected behavior**
There needs to be a way to select a host that's not one of the first 10.

**Screenshots**
![2024-09-28 19 04 19 ada manatee-bee ts net 25fbca5683e2](https://github.com/user-attachments/assets/06babc09-adb8-47ad-91b0-2daab9b43259)

![Screenshot from 2024-09-28 19-06-50](https://github.com/user-attachments/assets/4852cf00-9287-45c4-b9bf-382b56f2a056)

**(please complete the following information):**
 - OS: Pop_OS
 - Browser: Vivaldi
 - Version: 6.9

**Additional context**

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Archive password: changeme

you may need to install the c compiler

**Comment by SquirrelDeveloper** [comment]
Hi @btajuddin,
Thanks for your report, It seems to be a bug related to the pagination, I will take care of it soon,
Regards
