### ISSUE TITLE
[BUG] Unable to create sub-directory or playbook after creating new directory in Playbook tab

### ISSUE THREAD

**Issue by chrisbehectik** [SquirrelCorporation/SquirrelServersManager#336]
Hey, apologies in advance if you aren't expecting bug reports yet I understand it is still in development but thought I'd share.
Thanks for your work on the app, it's amazing! 

**Describe the bug**
Once I create a playbook directory under my user list I am unable to to create playbooks under it or sub-directories until I refresh the page

** Logs **
No relevant logs.

**To Reproduce**
1. Go to 'https://ssm.domain.com/manage/playbooks'.
2. Click on '+ Create'.
3. Select 'Repository path' 'user'.
4. Select 'Directory' and input name, ex: 'host-name'.
5. Click on '+ Create' again.
6. Select and expand repository path '/user/ and unable to see 'host-name'.

**Expected behavior**
After creating Playbook directory clicking create again should show new directory and be selectable to create new subdirectories or playbooks.

**Screenshots**
![playbook_bug](https://github.com/user-attachments/assets/dc73b9df-35c8-4a4c-b503-8eb0f7f6ae12)

**(please complete the following information):**
 - OS: Winows 11 Pro
 - Browser: Chrome Version 129.0.6668.60 (Official Build) (64-bit)
 - Version: SSM Version 0.1.18 

**Additional context**
Behind Nginx Proxy Manager and using SSL.

**Comment by SquirrelDeveloper** [comment]
Hi @chrisbehectik , Dont worry, bug reports are very welcome, on the contrary! It helps,
I am reproducing the bug and working on a fix,
Many thanks

**Comment by SquirrelDeveloper** [comment]
@chrisbehectik Fixed in future release 0.1.20
