### ISSUE TITLE
[BUG] sendDeviceInfoToApi 401 error

### ISSUE THREAD

**Issue by jhezjkp** [SquirrelCorporation/SquirrelServersManager#338]
**Describe the bug**

the server is deployed inside docker in an lan with cloudflared expose the port to public.

after install the agent, it failed to submit data to server

** Logs **
agent:

```
"level":"info","message":"[AGENT] [LOOP] - Agent health for 6e77282f-4e90-4496-9e51-c8f244decdfc","timestamp":"2024-10-05T03:21:00.455Z"}
{"level":"info","message":"Cron started (*/30 * * * * *)","timestamp":"2024-10-05T03:21:00.457Z"}
{"level":"info","message":"[AGENT] sendDeviceInfoToApi - To -> http://ssm.abcdef.xyz/api/devices/6e77282f-4e90-4496-9e51-c8f244decdfc","timestamp":"2024-10-05T03:21:03.064Z"}
{"level":"error","message":"Request failed with status code 401","timestamp":"2024-10-05T03:21:03.565Z"}
```

server log:

```
[03:09:03.885] INFO (1): [REST] - request received: GET - /devices/6e77282f-4e90-4496-9e51-c8f244decdfc
    module: "REST"
    req: {
      "id": 2773,
      "method": "GET",
      "url": "/devices/6e77282f-4e90-4496-9e51-c8f244decdfc",
      "query": {},
      "params": {},
      "headers": {
        "x-forwarded-for": "xx.xxx.xx.xxx, 192.168.144.1",
        "host": "server:3000",
        "connection": "close",
        "user-agent": "axios/1.7.4",
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip, br",
        "cdn-loop": "cloudflare; loops=1",
        "cf-connecting-ip": "xx.xxx.xx.xxx",
        "cf-ipcountry": "US",
        "cf-ray": "8cda35f27d9536aa-YYZ",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "cf-warp-tag-id": "f2c9c0ee-1f8e-428a-a1ee-a12b34987297",
        "x-forwarded-proto": "https"
      },
      "remoteAddress": "::ffff:192.168.144.6",
      "remotePort": 34132
    }
```

**Comment by SquirrelDeveloper** [comment]
Hi @jhezjkp 
Thanks for the report, however,
```json
{"level":"info","message":"[AGENT] sendDeviceInfoToApi - To -> http://ssm.abcdef.xyz/api/devices/6e77282f-4e90-4496-9e51-c8f244decdfc","timestamp":"2024-10-05T03:21:03.064Z"}
```
is a POST request to the server, and the server log you provided is from a GET request. Could you provide the failing POST request server's logs?

**Comment by SquirrelDeveloper** [comment]
Hi @jhezjkp . Are you able to simply get a response from the API by  calling http://ssm.abcdef.xyz/api/ping ?

**Comment by SquirrelDeveloper** [comment]
Hi @jhezjkp . A new version of SSM is available, with a Dockerized agent. Could you give it a try? It also should print more logs

**Comment by SquirrelDeveloper** [comment]
I would really like to help you but I am struggling to understand the problem.
- Are you able to curl the ping of SSM `from the host where is agent is not functioning` ?
- Is the domain behind cloudflare? Could it be your CDN blocking the request?

**Comment by SquirrelDeveloper** [comment]
Ok, lets investigate.
I have published a new version of the agent, supporting an additional env var called `DEBUG` (docker compose pull to retrieve it if you are using docker, or git pull if classic agent)
Restart the agent by adding `DEBUG=true` to the env and lets see the headers logs of response

**Comment by SquirrelDeveloper** [comment]
No ,problem @jhezjkp; Happy this is resolved
