### ISSUE TITLE
[BUG] some playbooks Fail to execute "Attempting to decrypt but no vault secrets found"

### ISSUE THREAD

**Issue by Cyborgninja21** [SquirrelCorporation/SquirrelServersManager#365]
**Describe the bug**
When attempting to execute some of the built-in playbooks ( _upgrade.yml as an example) on different test endpoints they with the 
following message 
<img width="591" alt="image" src="https://github.com/user-attachments/assets/eddd0f3a-2afc-4e55-8852-8b7975e708cb">

I'm guessing it's when the localized vault is trying to be decrypted that something's going awry.

And it's worth noting that I've tried destroying and recreating my install, and I'm currently using the default environment variables as called out on the example compose but I've attached my compose here just in case

**To Reproduce**
1. Attempt to run most of the built in Playbooks on a host
2. The playbook starts to execute the fails at gathering facts

**Expected behavior**
The playbook to fully execute

[squirrelserversmanager-compose.txt](https://github.com/user-attachments/files/17352764/squirrelserversmanager-compose.txt)

**Comment by SquirrelDeveloper** [comment]
Hi @Cyborgninja21 Thanks for the feedback. did you delete the volume (in your case ` ${PATH_TO_APPDATA}/SquirrelServersManager/database:/data/db`) ?
The data could have been saved with an old key

**Comment by SquirrelDeveloper** [comment]
Arf, too bad.
Could you try:
- In Settings - Playbooks (/admin/settings#playbooks) to put  "Log level of terminal" to 5 (max)
- In Inventory, <your device>, Configuration, in the modal, to re-enter the SSH creds, and click and "submit" 
<img width="915" alt="Screenshot 2024-10-14 at 16 50 46" src="https://github.com/user-attachments/assets/b0031a5b-9b05-4347-9c06-fe5733fb2bbf">

Then try again

**Comment by SquirrelDeveloper** [comment]
Oh, ok, thanks for the precision, with check or check diff, I am reproducing the bug, I am on it!
