### ISSUE TITLE
[BUG] Unable to execute playbook from remote get repository (request errored with status code: 500)

### ISSUE THREAD

**Issue by Cyborgninja21** [SquirrelCorporation/SquirrelServersManager#396]
**Describe the bug**
![image](https://github.com/user-attachments/assets/43f2290a-a678-46b4-8b23-0d8abcb03549)

I am unable to execute Any playbooks located within a get repository that I pull. The same exact playbooks will work when located locally and I even tried using some of the included playbooks with ssm and the result is the same as they all error out with the following message. 
([REST] - request errored with status code: 500)

** Logs **

![image](https://github.com/user-attachments/assets/23a17303-8503-4258-b439-ff4189a6d193)

**To Reproduce**
1. Open inventory menu
2. Attempt to execute any playbook located within Git repository

**Expected behavior**
Execution of the playbook on the chosen inventory device

**Comment by SquirrelDeveloper** [comment]
Hi!

Could you try in Settings / Advanced / Debug : `Purge & Sync Again` ?



Le dim. 20 oct. 2024 à 00:33, Chase Wallace ***@***.***> a
écrit :

**Comment by Cyborgninja21** [comment]
i gave that a run and it seems to complete with out issues (no errors in the log related that i can to it) But the outcome is all playbooks no longer populate within the UI.

and after force pulling again the playbooks re-populate but original issue returns (Status code:500)

is there an easy way for me to export the full log, ill add it here as the output of Purge & Sync is huge and i was not able to find anything that seems related.

**Comment by SquirrelDeveloper** [comment]
Ok, We may need to be it a little more technical here to understand what happen. It seems that is the ansible runner/cmd failing.
- First, is your repo a public one I can test myself or a private one?

Second, to debug, In the logs section, after a fail execution, could you:
- Click on the filter 'Module' and filter on `AnsibleShellCommandsManager`
<img width="1099" alt="Screenshot 2024-10-21 at 09 07 56" src="https://github.com/user-attachments/assets/7b35ef79-5c4e-42da-b46e-a9bf1eaff4ef">

- At one point, you should see 

```console
[ANSIBLE] - executePlaybook - Executing sudo SSM_API_KEY=XXX ....
```

- Copy the text from "sudo" until the end of the block
- Access a terminal inside SSM server container 
For example, on MacOs / Docker Desktop:
<img width="1124" alt="Screenshot 2024-10-21 at 09 13 31" src="https://github.com/user-attachments/assets/66984a0a-51df-4e06-9511-f1ec8563e4b5">
Other way to do it is `docker exec -it <container_id> /bin/sh`

Then,
- Once inside the docker ; enter ` cd /server/src/ansible` and copy paste the text you previously copied, and provide me with the output

**Comment by Cyborgninja21** [comment]
its private but i can likely open it up if you think it would be worth it.


* Once inside the docker ; enter  cd /server/src/ansible and copy paste the text you previously copied, and provide me with the output

see below for output


![image](https://github.com/user-attachments/assets/242d4da5-ee6c-4016-af6c-1710829b8a07)

**Comment by Cyborgninja21** [comment]
yep so renaming it to git-new-root-user-ansible.yml works
