### ISSUE TITLE
[FEATURE] add (re)initialize action to the git actions menu

### ISSUE THREAD

**Issue by Cyborgninja21** [SquirrelCorporation/SquirrelServersManager#422]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/ba819730-dfdb-4352-bbeb-3ccb8425e72b)

I persist all of the folders  for Squirrel manager on an NFS and I've noticed that when I destroy it and recreate it the GIT repositories that I have saved to the current instance need to be reinitialized every time I turn it back up. 

This requires me to remove the entire entry and  re-add it. 
whereas it would be simpler I think to just have a reinitialize option since all of the pertinent information is locally stored already.

![image](https://github.com/user-attachments/assets/85451e2f-b9c8-4d1b-bfe2-044a72b03976)

**Comment by SquirrelDeveloper** [comment]
Hi @Cyborgninja21 . To understand the underlying problem well, could you tell me what do you mean by `when I destroy it and recreate it `?

**Comment by SquirrelDeveloper** [comment]
@Cyborgninja21 I will close the issue soon. Did you have a look at my question?
