### ISSUE TITLE
[BUG] Container detection and deployment

### ISSUE THREAD

**Issue by habibullinrsh** [SquirrelCorporation/SquirrelServersManager#440]
**Describe the bug**
- After installing the agent in the docker container, it detects only newly launched containers. In order for him to add new sms containers, you need to restart them all.
- I am adding nodes with private key authorization. Installing the agent in the docker container. After a further attempt to install a new stack, the sms returns a ssh connection error.

** Logs **
[server.log](https://github.com/user-attachments/files/17644335/server.log)
[ping-success.log](https://github.com/user-attachments/files/17644385/ping-success.log)

**To Reproduce**
1.
- Run on the server ssm - "docker compose up -d"
- Add a new server and install the agent in the docker container
- Go to the Containers tab and click Refresh (I've been waiting for hours)
- Connect to the server with the installed ssm restart (docker compose down && docker compose up -d)
- Containers appear in the Containers tab
2.
- I will add a new server (Device IP - ...; Strict Host Checking - true; Connection Method - ssh or paramiko; Sudo Method - sudo; Sudo User - admin; SSH Connection Type - Keys; SSH User Name - admin; SSH Private Key - ...)
- Test connections - success
- Dockerized Agent (Experimental) - success
- First ping - success
- First deploy - success
- After restart ssm-server - error, but using the connect button I can connect to the server

**Expected behavior**
Successful deployment

**Screenshots**
![image](https://github.com/user-attachments/assets/9b6f9b1f-1398-4f8c-b19e-8a9d232da549)

**(please complete the following information):**
 - Ubuntu 24.04.1 LTS
 - Yandex Browser
 - Docker 27.3.1

**Additional context**

**Comment by habibullinrsh** [comment]
Before restarting the ssh server, the private keys in /tmp are not encrypted. After the restart, the keys are placed in the ansible vault. It seems that ssm does not decrypt them when pinging or deploying, so an error occurs.

Before the restart
![image](https://github.com/user-attachments/assets/9c50c1dc-0dd4-4352-8b4c-41090ac885f5)

After the restart
![image](https://github.com/user-attachments/assets/0abb9c92-e687-4167-bafd-3547e5215db6)

**Comment by SquirrelDeveloper** [comment]
Hi @habibullinrsh Thank you very much for the report.
I have found the origin of the second problem. I will have to investigate further for your first one.

**Comment by habibullinrsh** [comment]
Thank you for your cool project :)

**Comment by SquirrelDeveloper** [comment]
Fixed for future release v0.1.22
