### ISSUE TITLE
[BUG] Container image tags

### ISSUE THREAD

**Issue by habibullinrsh** [SquirrelCorporation/SquirrelServersManager#441]
**Describe the bug**
1. When using a fixed ssm services image tag, the tag of the available update is displayed incorrectly.
2. I can specify two image names from the docker hub, for example nginx and nginx/nginx-ingress. In the first case it is displayed as library/nginx, in the second it is correct.

** Logs **
I didn't find it.

**To Reproduce**
1.
 - Launch ssm services with the v0.1.21 tag
 - Wait for changes in the available version
 2.
 - Run two images from the docker hub

**Expected behavior**
1. Displaying an available update with the correct tag
2. Displaying the image name without library/

**Screenshots**
1.
![image](https://github.com/user-attachments/assets/2d06a4b7-8bc2-4992-b316-23795b9121ee)
![image](https://github.com/user-attachments/assets/ee9f4a60-e0ad-4004-a97e-33428c68b4a0)
![image](https://github.com/user-attachments/assets/2b0a5dc3-e718-46a8-a791-b8ed8d0cde32)
2.
![image](https://github.com/user-attachments/assets/3e33f7b3-3d61-40cb-baa2-a3678cbb3ea6)
![image](https://github.com/user-attachments/assets/3674d117-0406-4201-a1c3-ed5d515f86b1)

**(please complete the following information):**
 - Ubuntu 24.04.1 LTS
 - Yandex Browser
 - Docker 27.3.1

**Additional context**

**Comment by SquirrelDeveloper** [comment]
Hi @habibullinrsh 
I have investigated and found one possible improvements.
However, regarding the `library/` , nothing to be done, that how the docker registry presents itself https://github.com/docker-library/official-images/tree/master/library
