### ISSUE TITLE
[FEATURE] Provide a confirmation before reboot.

### ISSUE THREAD

**Issue by windware-ono** [SquirrelCorporation/SquirrelServersManager#458]
**Is your feature request related to a problem? Please describe.**
It should provide a confirmation before rebooting as simple mistake could lead to a trouble on an unexpected reboot.

**Describe the solution you'd like**
Provide some sort of confirmation to cancel reboot.

**Comment by SquirrelDeveloper** [comment]
Good input, I will add it
