### ISSUE TITLE
[FEAT] Playbooks - Support directories & Git sync

### ISSUE THREAD

**Issue by SquirrelDeveloper** [SquirrelCorporation/SquirrelServersManager#48]
Add the ability to manage directories in Playbooks, as well as adding Git repo to sync external playbooks

**Comment by SquirrelDeveloper** [comment]
Its gonna be a huge, huge one update

**Comment by chopeta** [comment]
> Its gonna be a huge, huge one update

Anxiously waiting for the next release.

Would be possible to include the ability to schedule playbook execution? I need it so much :-)
