### ISSUE TITLE
[BUG] Response status: 500 - _checkDeviceBeforeAdd.yml not found.

### ISSUE THREAD

**Issue by luismanson** [SquirrelCorporation/SquirrelServersManager#488]
**Describe the bug**
Clean install using proxmox deploy script, I have conected a server but it seems some files are missing. so i receive errors like:
` Response status: 500 - _checkDeviceBeforeAdd.yml not found.` 

After looking at the docs, it seems my ssm-core and ssm-tools repositories are empty. I did not see any way to populate the standard files.

Is there any steps im missing or some log where I can check what's happening here?

**Comment by SquirrelDeveloper** [comment]
Hi @luismanson 
Could you try to reset the playbooks module here ?
<img width="1618" alt="Screenshot 2024-11-17 at 08 55 41" src="https://github.com/user-attachments/assets/44718b96-a0ac-45a5-9b80-71a4f229d410">

**Comment by luismanson** [comment]
Thanks! that did the trick. I also kept receiving `ENOENT: no such file or directory, open '/data/config/ansible.cfg'` in the advanced settings tab. 
I've created an empty one in that location and now it seems to be working.

thanks!

**Comment by SquirrelDeveloper** [comment]
Been fixed, in a future realse

**Comment by itsfeng** [comment]
@SquirrelDeveloper : Having the same issue. `Purge & Sync` did not help  

Server Information Version: 0.1.26
Installation Method: Quick Start Docker Script

Am happy to provide more details if needed.

**Comment by SquirrelDeveloper** [comment]
Hi @itsfeng , thanks for your report,
Could you post here the related error logs (you should be able to find them in "Logs" and filter by Level = error
