### ISSUE TITLE
[BUG] Ratelimited by docker seems like container update cron task is responsible

### ISSUE THREAD

**Issue by Buco7854** [SquirrelCorporation/SquirrelServersManager#546]
**Describe the bug**
I am not quite sure about it but every hour it seems like a task to check if a container update is available is launched. And i think i'm getting ratelimited by docker hub cause of it.

**Logs**

![image](https://github.com/user-attachments/assets/cfd8e9c2-4bcc-409f-aaf6-842dc7ef292d)
![image](https://github.com/user-attachments/assets/c6ac7408-fef6-4af7-9c08-e6e87939631b)

**To Reproduce**
Add some new machine in the inventory.
After clicking on refresh button manually you can see the same behaviour as the one that is hapening every hour.

**Expected behavior**
At least some option to disable this update check. When you have hundres of container it does a lot of request :)

**(please complete the following information):**
 - OS: debian 12 bookworm
 - Version 0.1.21

**Comment by SquirrelDeveloper** [comment]
Hi @Buco7854 . Thanks for the feedback. 
The default value may be a little high, you are right.
In the mean time, it is something you can change in the device configuration: 
https://squirrelserversmanager.io/docs/technical-guide/docker#options

**Comment by SquirrelDeveloper** [comment]
<img width="904" alt="docker-options" src="https://github.com/user-attachments/assets/eec42ae9-2e1e-49d3-abb9-0c6f424062f1">

**Comment by Buco7854** [comment]
Oh did not know you could edit it sorry 
I just disabled watch container since it's not a feature I'm using.

Thanks.
