### ISSUE TITLE
Invalid Project Name Error in Deploy Custom Stack Compose

### ISSUE THREAD

**Issue by merzzzl** [SquirrelCorporation/SquirrelServersManager#555]
An error occurs when executing the Deploy Custom Stack playbook due to invalid project name generation for Docker Compose. The generated name includes an underscore (_) and (.), which is not permitted in Docker Compose project names.

I'm not good at Typescript, but I can assume that the problem comes from this method:
https://github.com/SquirrelCorporation/SquirrelServersManager/blob/dae61cd9ec848ad0d3f2bda077c9a5f53fb67702/server/src/modules/repository/ContainerCustomStacksRepositoryComponent.ts#L157-L159

it may be worth using "-" instead of "_", or the ideal solution would be to check for the presence of "name:" at the root to be able to costamize project names and not use the extension in the name.

because in the future this name is passed as project in the playbook:
https://github.com/SquirrelCorporation/SquirrelServersManager/blob/dae61cd9ec848ad0d3f2bda077c9a5f53fb67702/server/src/controllers/rest/containers/stacks.ts#L187

in the playbook, we shift project to project_name:
https://github.com/SquirrelCorporation/SquirrelServersManager/blob/dae61cd9ec848ad0d3f2bda077c9a5f53fb67702/server/src/ansible/00000000-0000-0000-0000-000000000000/docker/_dockerCompose.yml#L22

which is used in community.docker.docker_compose_v2

I think using "name" would be the best option:
https://docs.docker.com/reference/compose-file/version-and-name/#name-top-level-element

**Comment by SquirrelDeveloper** [comment]
Hi @merzzzl,
Thank you for your report, I will fix it asap,
Regards

**Comment by merzzzl** [comment]
if someone has a similar problem, you can temporarily change '{{ project }}' to '{{ project.split("_")[0] }}' in 
Playbooks -> ssm-core -> docker -> '_dockerCompose.yml'
