### ISSUE TITLE
[BUG] Container Stack Bugs

### ISSUE THREAD

**Issue by merzzzl** [SquirrelCorporation/SquirrelServersManager#577]
**Describe the bug**
When editing any existing containerStack (yaml), the lockJson flag is lost.

**Logs**
Befor Edit:
```
{
    "_id": "6761497228aa8b296e4c481b",
    "uuid": "01f08205-7c52-4945-b418-a6405b7716e3",
    "createdAt": "2024-12-17T09:50:42.760Z",
    "lockJson": true,
    "name": "boring-shockley",
    "type": "local",
    "updatedAt": "2024-12-17T09:54:14.316Z",
    "yaml": "services:\n    test:\n        iamge: test"
}
```
After Edit:
```
{
    "_id": "6761497228aa8b296e4c481b",
    "uuid": "01f08205-7c52-4945-b418-a6405b7716e3",
    "createdAt": "2024-12-17T09:50:42.760Z",
    "lockJson": false,
    "name": "boring-shockley",
    "type": "local",
    "updatedAt": "2024-12-17T09:56:06.545Z",
    "yaml": "services:\n    test:\n        iamge: test"
}
```

**To Reproduce**
Create and then edit any Container Stack in yaml.

**Additional context**
I will assume that it is enough to add `setLockUI(true);` at this point and this will solve the problem.
https://github.com/SquirrelCorporation/SquirrelServersManager/blob/19946a8f9d617b7713f04f745663b19ac31a5cac/client/src/pages/ComposeEditor/index.tsx#L120-L122

**Comment by merzzzl** [comment]
**Describe the bug**
Volume parsing error in UI when creating Container Stack (api/containers/custom-stacks/transform)

**Logs**
Req:
```
{"content":"{\"name\":\"nervous-agnesi\",\"services\":{\"lipGaUFt7T\":{\"name\":\"test\",\"service-volumes\":[{\"source\":\"ok\",\"target\":\"/ok\"}]}}}"}
```
Resp:
```
{
    "success": true,
    "message": "Post Transform Custom Stack",
    "data": {
        "yaml": "services:\n  test: {}\n"
    }
}
```

**To Reproduce**
Create Stack in UI with service volume and try edit in code editor.

**Additional context**
Perhaps the reason is that in json it is not volumes but service-volumes.
https://github.com/SquirrelCorporation/SquirrelServersManager/blob/19946a8f9d617b7713f04f745663b19ac31a5cac/server/src/helpers/docker/DockerComposeJSONTransformer.ts#L41C9-L41C90

**Comment by SquirrelDeveloper** [comment]
> **Describe the bug** When editing any existing containerStack (yaml), the lockJson flag is lost.
> 
> **Logs** Befor Edit:
> 
> ```
> {
>     "_id": "6761497228aa8b296e4c481b",
>     "uuid": "01f08205-7c52-4945-b418-a6405b7716e3",
>     "createdAt": "2024-12-17T09:50:42.760Z",
>     "lockJson": true,
>     "name": "boring-shockley",
>     "type": "local",
>     "updatedAt": "2024-12-17T09:54:14.316Z",
>     "yaml": "services:\n    test:\n        iamge: test"
> }
> ```
> 
> After Edit:
> 
> ```
> {
>     "_id": "6761497228aa8b296e4c481b",
>     "uuid": "01f08205-7c52-4945-b418-a6405b7716e3",
>     "createdAt": "2024-12-17T09:50:42.760Z",
>     "lockJson": false,
>     "name": "boring-shockley",
>     "type": "local",
>     "updatedAt": "2024-12-17T09:56:06.545Z",
>     "yaml": "services:\n    test:\n        iamge: test"
> }
> ```
> 
> **To Reproduce** Create and then edit any Container Stack in yaml.
> 
> **Additional context** I will assume that it is enough to add `setLockUI(true);` at this point and this will solve the problem.
> 
> https://github.com/SquirrelCorporation/SquirrelServersManager/blob/19946a8f9d617b7713f04f745663b19ac31a5cac/client/src/pages/ComposeEditor/index.tsx#L120-L122

Hi,
Awesome finding, I am reproducing it, will fix

**Comment by SquirrelDeveloper** [comment]
> **Describe the bug** Volume parsing error in UI when creating Container Stack (api/containers/custom-stacks/transform)
> 
> **Logs** Req:
> 
> ```
> {"content":"{\"name\":\"nervous-agnesi\",\"services\":{\"lipGaUFt7T\":{\"name\":\"test\",\"service-volumes\":[{\"source\":\"ok\",\"target\":\"/ok\"}]}}}"}
> ```
> 
> Resp:
> 
> ```
> {
>     "success": true,
>     "message": "Post Transform Custom Stack",
>     "data": {
>         "yaml": "services:\n  test: {}\n"
>     }
> }
> ```
> 
> **To Reproduce** Create Stack in UI with service volume and try edit in code editor.
> 
> **Additional context** Perhaps the reason is that in json it is not volumes but service-volumes. https://github.com/SquirrelCorporation/SquirrelServersManager/blob/19946a8f9d617b7713f04f745663b19ac31a5cac/server/src/helpers/docker/DockerComposeJSONTransformer.ts#L41C9-L41C90

Thanks again, report like that are easy to fix, I will merge the fix soon and release a new SSM version by the end of week 🔥

**Comment by merzzzl** [comment]
That's good news! Thanks!
