### ISSUE TITLE
[FEATURE] Add Gitea

### ISSUE THREAD

**Issue by merzzzl** [SquirrelCorporation/SquirrelServersManager#581]
**Describe the solution you'd like**
Although Gitea support has not been announced, it works, but you have to specify it in the URL like this: "https://user:token@git.example.com/your/repo.git "and it's okay, may be add support in UI, because token in url is unsafe

P.S.
when test I add Gitea as GitHub client

**Comment by SquirrelDeveloper** [comment]
Hi @merzzzl ,
Thank you very much for your feedback,
I will test it and add it asap
