### ISSUE TITLE
[FEATURE] History of output for Ansible playbook executions

### ISSUE THREAD

**Issue by ShaBangBinBash** [SquirrelCorporation/SquirrelServersManager#598]
**Is your feature request related to a problem? Please describe.**
There is a log of the status of each playbook execution in Task Logs, but I cannot find the output of what was executed.
This means that I cannot go back and look at previous executions to see what failed or (in a success) what was changed.

**Describe the solution you'd like**
A copy of the output of each Ansible playbook run is kept (can be file on disk which can make them accessible outside of Docker for other tools).
Additionally in the log of executions a button to display the output on screen. Color would be nice but is not a necessity.

**Comment by SquirrelDeveloper** [comment]
Hi @ShaBangBinBash . Thanks for the feedback, I will see what I can do to improve it
