### ISSUE TITLE
[FEATURE] Enter Vault Password

### ISSUE THREAD

**Issue by powerpaul17** [SquirrelCorporation/SquirrelServersManager#609]
**Is your feature request related to a problem? Please describe.**
I cannot find any place to enter an ansible vault password.

**Describe the solution you'd like**
A possibility to enter/save an ansible vault password.

**Comment by SquirrelDeveloper** [comment]
Hi @powerpaul17. The Vault password is defined in `.env` file under "VAULT_PWD"

**Comment by powerpaul17** [comment]
Thanks for the info. But there is no possibility to have a vault password for each repository?

**Comment by SquirrelDeveloper** [comment]
@powerpaul17 . No, it is not possible. SSM uses a single vault, because some values are stored in the database and passed encrypted to Ansible.

**Comment by powerpaul17** [comment]
Ok, i see. But I have a vault in my repository and cannot run any playbook without a vault password.

**Comment by SquirrelDeveloper** [comment]
@powerpaul17 Interesting. It could be supported, do you have an example of it?

**Comment by powerpaul17** [comment]
I am not sure what example you need, but I can explain my setup. In the repository are encrypted config files which have to be decrypted by ansible using a vault password. This can be a different one for each respository. Semaphore-UI has the functionality for that for example.

**Comment by SquirrelDeveloper** [comment]
Got it, will look at Semaphore

**Comment by SquirrelDeveloper** [comment]
@powerpaul17 Moved to feature req
