### ISSUE TITLE
SSH Connection error if not on port 22

### ISSUE THREAD

**Issue by gmsh-1** [SquirrelCorporation/SquirrelServersManager#65]
For the life of me i couldn't establish a connection on a machine that I had changed the ssh port to other than 22, call it xxxx. I could Putty just fine to the machine, as i always have.

After i manually installed the agent and changed the port in the config to xxxx, i tried to ping it and saw that i was getting errors trying to connect to the machine on port 22 (it specifically said something like unable to connect to 192.168.xx.y on port 22). The port xxxx wouldn't stick to the change.

I restarted the machine, docker container with no success.

After changing the port on the machine to 22 i was able to ping and push updates and everything seems to work fine.

Sorry i don't have the logs, if need be i can revert the port back and replicate.

**Comment by SquirrelDeveloper** [comment]
@gmsh-1 I found the problem, PR is on the way and fix for the next release

**Comment by gmsh-1** [comment]
@SquirrelDeveloper thank you for all the hard work your are putting in this.
