### ISSUE TITLE
[BUG] e.slice is not a function on services page, no default playbooks present?

### ISSUE THREAD

**Issue by arminus** [SquirrelCorporation/SquirrelServersManager#67]
**Describe the bug**
e.slice is not a function on services page

**To Reproduce**
Device (the host where the container is running on) is listed w/o apparent problems, however, there also seems to be a problwm with the default playbooks. Trying to retrieve the agent's logs results in this:

![2024-07-02_100744](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/683680/df2ea2fb-5dd1-4c14-ab0c-85bbc590dfdf)

I did add the new server volume
```
    volumes:
      - ./.data.prod/playbooks:/playbooks
```
But that directory is obviously empty.

**Screenshots**
![2024-07-02_094546](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/683680/e4d3c6e4-e4fc-4aca-bd20-e619912c4cf3)

**(please complete the following information):**
 - OS: Pi4/aarch64/Debian11
 - Browser: Firefox
 - Version: SSM 0.1.14

**Additional context**
Wasn't able to setup a dev env yet, docker-compose on that pi can't handle build additional_contexts and target attributes.

**Comment by SquirrelDeveloper** [comment]
Hi @arminus Are you sure the server is updated to the latest version ?  (Go to the Settings / System Information)
Ensure to do a `docker-compose pull` to be sure
Also, are you able to show the logs related to this error by providing a capture of the table in the "Logs" page?

**Comment by arminus** [comment]
Yes, for some reason, the first compose up pulled the 0.1.14 client, but not the server. Pulled that explicitly, restarted, error is gone, but I still don't see the containers:

![2024-07-02_110126](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/683680/2bf071f9-f03a-475c-a1de-b511e2003691)

**Comment by SquirrelDeveloper** [comment]
Thanks @arminus for confirming it. I found some cases where the slice could crash, preparing a PR. 
As for your capture, you may need to adjust the docker connection settings, could you try, in " Inventory / Configuration / Connection test " to run the connection test and see if there are any errors, and copy paste here the errors if so? Thanks

**Comment by arminus** [comment]
Right, I think I had used the wrong sudo passwd. Now everything is fine. Thanks for the quick responses!
