### ISSUE TITLE
[BUG] Agent overrides IP to LAN

### ISSUE THREAD

**Issue by Codycody31** [SquirrelCorporation/SquirrelServersManager#94]
**Logs**
[https://link.codycody31.dev/u/oo0Dax.png](https://zipline.codycody31.dev/u/oo0Dax.png)

**To Reproduce**
1. Add an agent on a OS that doesn't have the network configured to know what it's own IP is

**Expected behavior**
Add the ability to override the IP of a device and ensure the agent on said device can no longer change it back. As in some cases the agent will set `10.0.0.5` or whatever.

**Comment by SquirrelDeveloper** [comment]
@Codycody31 thanks for the feedback, will select this feature for next release, which focus on strenghtening the agent installation and options

**Comment by SquirrelDeveloper** [comment]
@Codycody31 You can no manually add in the agent environment (.env file) the variable `OVERRIDE_IP_DETECTION` that contains the fixed IP.
Further agent parameters and settings from the UI will come in later versions
